# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meta.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='meta.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nmeta.proto\"^\n\x0fRequestEnvelope\x12!\n\x07payload\x18\x01 \x01(\x0b\x32\x10.MetadataRequest\x12\x16\n\x0e\x63lient_version\x18\x03 \x01(\t\x12\x10\n\x08rpc_name\x18\x05 \x01(\t\"6\n\x10ResponseEnvelope\x12\"\n\x07payload\x18\x01 \x01(\x0b\x32\x11.MetadataResponse\"3\n\x0fMetadataRequest\x12 \n\x0b\x64\x65vice_info\x18\x01 \x01(\x0b\x32\x0b.DeviceInfo\"A\n\nDeviceInfo\x12!\n\x08platform\x18\x01 \x01(\x0e\x32\x0f.DevicePlatform\x12\x10\n\x08gpu_name\x18\x03 \x01(\t\"\xa5\x01\n\x10MetadataResponse\x12\x16\n\x0e\x62undle_version\x18\x01 \x01(\t\x12\x18\n\x10gamedata_version\x18\x02 \x01(\t\x12\x14\n\x0c\x63\x64n_base_url\x18\x03 \x01(\t\x12\x13\n\x0bloc_version\x18\x04 \x01(\t\x12\x18\n\x10loc_cdn_base_url\x18\x05 \x01(\t\x12\x1a\n\x12\x61sset_cdn_base_url\x18\x06 \x01(\t\";\n\x13\x41ssetBundleMetadata\x12$\n\x0b\x62undle_info\x18\x01 \x03(\x0b\x32\x0b.BundleInfoB\x02\x10\x00\"z\n\nBundleInfo\x12\x13\n\x0b\x62undle_name\x18\x01 \x01(\t\x12\x1a\n\x12\x64ownload_size_byte\x18\x02 \x01(\x04\x12\x16\n\x0e\x64ownload_order\x18\x03 \x01(\x05\x12\x0b\n\x03\x63rc\x18\x04 \x01(\x04\x12\x16\n\x0etutorial_asset\x18\x05 \x01(\x08*c\n\x0e\x44\x65vicePlatform\x12\x1b\n\x17INVALID_DEVICE_PLATFORM\x10\x00\x12\x17\n\x13IOS_DEVICE_PLATFORM\x10\x01\x12\x1b\n\x17\x41NDROID_DEVICE_PLATFORM\x10\x02\x62\x06proto3'
)

_DEVICEPLATFORM = _descriptor.EnumDescriptor(
  name='DevicePlatform',
  full_name='DevicePlatform',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID_DEVICE_PLATFORM', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='IOS_DEVICE_PLATFORM', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ANDROID_DEVICE_PLATFORM', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=639,
  serialized_end=738,
)
_sym_db.RegisterEnumDescriptor(_DEVICEPLATFORM)

DevicePlatform = enum_type_wrapper.EnumTypeWrapper(_DEVICEPLATFORM)
INVALID_DEVICE_PLATFORM = 0
IOS_DEVICE_PLATFORM = 1
ANDROID_DEVICE_PLATFORM = 2



_REQUESTENVELOPE = _descriptor.Descriptor(
  name='RequestEnvelope',
  full_name='RequestEnvelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='RequestEnvelope.payload', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_version', full_name='RequestEnvelope.client_version', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rpc_name', full_name='RequestEnvelope.rpc_name', index=2,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=108,
)


_RESPONSEENVELOPE = _descriptor.Descriptor(
  name='ResponseEnvelope',
  full_name='ResponseEnvelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='ResponseEnvelope.payload', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=164,
)


_METADATAREQUEST = _descriptor.Descriptor(
  name='MetadataRequest',
  full_name='MetadataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_info', full_name='MetadataRequest.device_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=217,
)


_DEVICEINFO = _descriptor.Descriptor(
  name='DeviceInfo',
  full_name='DeviceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='platform', full_name='DeviceInfo.platform', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gpu_name', full_name='DeviceInfo.gpu_name', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=284,
)


_METADATARESPONSE = _descriptor.Descriptor(
  name='MetadataResponse',
  full_name='MetadataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bundle_version', full_name='MetadataResponse.bundle_version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gamedata_version', full_name='MetadataResponse.gamedata_version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cdn_base_url', full_name='MetadataResponse.cdn_base_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loc_version', full_name='MetadataResponse.loc_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='loc_cdn_base_url', full_name='MetadataResponse.loc_cdn_base_url', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='asset_cdn_base_url', full_name='MetadataResponse.asset_cdn_base_url', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=452,
)


_ASSETBUNDLEMETADATA = _descriptor.Descriptor(
  name='AssetBundleMetadata',
  full_name='AssetBundleMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bundle_info', full_name='AssetBundleMetadata.bundle_info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=454,
  serialized_end=513,
)


_BUNDLEINFO = _descriptor.Descriptor(
  name='BundleInfo',
  full_name='BundleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bundle_name', full_name='BundleInfo.bundle_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='download_size_byte', full_name='BundleInfo.download_size_byte', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='download_order', full_name='BundleInfo.download_order', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='crc', full_name='BundleInfo.crc', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tutorial_asset', full_name='BundleInfo.tutorial_asset', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=637,
)

_REQUESTENVELOPE.fields_by_name['payload'].message_type = _METADATAREQUEST
_RESPONSEENVELOPE.fields_by_name['payload'].message_type = _METADATARESPONSE
_METADATAREQUEST.fields_by_name['device_info'].message_type = _DEVICEINFO
_DEVICEINFO.fields_by_name['platform'].enum_type = _DEVICEPLATFORM
_ASSETBUNDLEMETADATA.fields_by_name['bundle_info'].message_type = _BUNDLEINFO
DESCRIPTOR.message_types_by_name['RequestEnvelope'] = _REQUESTENVELOPE
DESCRIPTOR.message_types_by_name['ResponseEnvelope'] = _RESPONSEENVELOPE
DESCRIPTOR.message_types_by_name['MetadataRequest'] = _METADATAREQUEST
DESCRIPTOR.message_types_by_name['DeviceInfo'] = _DEVICEINFO
DESCRIPTOR.message_types_by_name['MetadataResponse'] = _METADATARESPONSE
DESCRIPTOR.message_types_by_name['AssetBundleMetadata'] = _ASSETBUNDLEMETADATA
DESCRIPTOR.message_types_by_name['BundleInfo'] = _BUNDLEINFO
DESCRIPTOR.enum_types_by_name['DevicePlatform'] = _DEVICEPLATFORM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestEnvelope = _reflection.GeneratedProtocolMessageType('RequestEnvelope', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTENVELOPE,
  '__module__' : 'meta_pb2'
  # @@protoc_insertion_point(class_scope:RequestEnvelope)
  })
_sym_db.RegisterMessage(RequestEnvelope)

ResponseEnvelope = _reflection.GeneratedProtocolMessageType('ResponseEnvelope', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEENVELOPE,
  '__module__' : 'meta_pb2'
  # @@protoc_insertion_point(class_scope:ResponseEnvelope)
  })
_sym_db.RegisterMessage(ResponseEnvelope)

MetadataRequest = _reflection.GeneratedProtocolMessageType('MetadataRequest', (_message.Message,), {
  'DESCRIPTOR' : _METADATAREQUEST,
  '__module__' : 'meta_pb2'
  # @@protoc_insertion_point(class_scope:MetadataRequest)
  })
_sym_db.RegisterMessage(MetadataRequest)

DeviceInfo = _reflection.GeneratedProtocolMessageType('DeviceInfo', (_message.Message,), {
  'DESCRIPTOR' : _DEVICEINFO,
  '__module__' : 'meta_pb2'
  # @@protoc_insertion_point(class_scope:DeviceInfo)
  })
_sym_db.RegisterMessage(DeviceInfo)

MetadataResponse = _reflection.GeneratedProtocolMessageType('MetadataResponse', (_message.Message,), {
  'DESCRIPTOR' : _METADATARESPONSE,
  '__module__' : 'meta_pb2'
  # @@protoc_insertion_point(class_scope:MetadataResponse)
  })
_sym_db.RegisterMessage(MetadataResponse)

AssetBundleMetadata = _reflection.GeneratedProtocolMessageType('AssetBundleMetadata', (_message.Message,), {
  'DESCRIPTOR' : _ASSETBUNDLEMETADATA,
  '__module__' : 'meta_pb2'
  # @@protoc_insertion_point(class_scope:AssetBundleMetadata)
  })
_sym_db.RegisterMessage(AssetBundleMetadata)

BundleInfo = _reflection.GeneratedProtocolMessageType('BundleInfo', (_message.Message,), {
  'DESCRIPTOR' : _BUNDLEINFO,
  '__module__' : 'meta_pb2'
  # @@protoc_insertion_point(class_scope:BundleInfo)
  })
_sym_db.RegisterMessage(BundleInfo)


_ASSETBUNDLEMETADATA.fields_by_name['bundle_info']._options = None
# @@protoc_insertion_point(module_scope)
